//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class baseprod2Entities : DbContext
    {
        public baseprod2Entities()
            : base("name=baseprod2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_S_LeadsNoProcesados_Scotiabank_Result> SP_S_LeadsNoProcesados_Scotiabank()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_S_LeadsNoProcesados_Scotiabank_Result>("SP_S_LeadsNoProcesados_Scotiabank");
        }
    
        public virtual ObjectResult<SP_U_MarcaLeads_Scotiabank_Result> SP_U_MarcaLeads_Scotiabank(string rut, string telefono, string email, Nullable<int> monto_credito, Nullable<int> nro_cuotas, Nullable<int> valor_cuota)
        {
            var rutParameter = rut != null ?
                new ObjectParameter("rut", rut) :
                new ObjectParameter("rut", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var monto_creditoParameter = monto_credito.HasValue ?
                new ObjectParameter("monto_credito", monto_credito) :
                new ObjectParameter("monto_credito", typeof(int));
    
            var nro_cuotasParameter = nro_cuotas.HasValue ?
                new ObjectParameter("nro_cuotas", nro_cuotas) :
                new ObjectParameter("nro_cuotas", typeof(int));
    
            var valor_cuotaParameter = valor_cuota.HasValue ?
                new ObjectParameter("valor_cuota", valor_cuota) :
                new ObjectParameter("valor_cuota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_U_MarcaLeads_Scotiabank_Result>("SP_U_MarcaLeads_Scotiabank", rutParameter, telefonoParameter, emailParameter, monto_creditoParameter, nro_cuotasParameter, valor_cuotaParameter);
        }
    }
}
